build:
  image: default-jammy
  environment:
    php: 8.2.15
  nodes:
    analysis:
      tests:
        override:
          # Add the respective Scrutinizer analysis for your language like
          - php-scrutinizer-run

filter:
  excluded_paths: [tests/*]