filter:
  excluded_paths:
    - 'tests/*'
checks:
  php: true

build:
  image: default-jammy
  environment:
    php: 8.2.15
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - command: php -d debug.mode=coverage ./vendor/bin/phpunit
            coverage:
              file: coverage.clover
              format: clover