build:
  image: default-jammy
  environment:
    php: 8.2.16
  nodes:
    analysis:
      dependencies:
        before:
          - sudo apt-get install bzip2
      tests:
        override:
          # Add the respective Scrutinizer analysis for your language like
          - php-scrutinizer-run

filter:
  excluded_paths: [tests/*]