build:
  image: default-jammy
  environment:
    dependencies:
      before:
        - sudo apt-get install bzip2
    php: 8.2.16
  nodes:
    analysis:
      tests:
        override:
          # Add the respective Scrutinizer analysis for your language like
          - php-scrutinizer-run

filter:
  excluded_paths: [tests/*]