name: Integration Workflow

on:
  - push
  - pull_request

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2', '8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setting up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Installing Composer
        run: composer install ${{ env.COMPOSER_FLAGS }}

      - name: "Run tests"
        run: "vendor/bin/phpunit"

      - name: "Run mess detection"
        run: "vendor/bin/phpmd src text build/phpmd.xml "

      - name: "Run code analysis"
        run: "vendor/bin/phpstan --no-ansi --no-interaction"